[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.virtualenv"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m virtualenv /app/venv",
  "/app/venv/bin/pip install yfinance scipy numpy --quiet"
]

[start]
cmd = "node dist/index.cjs"
