[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python312",
  "python312Packages.yfinance",
  "python312Packages.scipy",
  "python312Packages.numpy"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm run build && node dist/index.cjs"
