[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./run_with_daemon.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "ALWAYS"
restartPolicyMaxRetries = 10
sleepApplication = false
numReplicas = 1
