// aeroBake.test.ts — our own FAA chart bake as a tile source: manifest
// validation, the "effective AND newer than the FAA service" switch rule,
// range reads against a PMTiles archive written by the bake's own Python
// writer (server/__fixtures__/faa_bake_fixture.pmtiles, regenerated by
// scripts/faa_charts/make_fixture.py), and the aeroCharts integration:
// tiles, status/registry, prefetch skip, and the fallback when the bucket
// cannot be read.

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "fs";
import os from "os";
import path from "path";

import { AERO_BAKE_MANIFEST_KEY, chooseBake, createBakeReader, parseBakeManifest, RangeFetchSource } from "./aeroBake";
import { AERO_CHART_IDS, createAeroChartService, editionInfo, handleAeroTile, sniffImageType } from "./aeroCharts";

const here = path.dirname(new URL(import.meta.url).pathname);
const FIXTURE = fs.readFileSync(path.join(here, "__fixtures__", "faa_bake_fixture.pmtiles"));
const BASE = "https://bake.example";
const NOW = Date.parse("2026-10-06T12:00:00Z");

function entry(edition: string, extra: Record<string, unknown> = {}) {
  return {
    edition, key: `tiles/faa/sectional/${edition}.pmtiles`, min_zoom: 2, max_zoom: 11, faa_min_zoom: 8,
    baked_at: "2026-10-06T10:00:00+00:00", charts: 56,
    verify: { coverage: 0.999, spill: 0.0001, median_structural_diff: 9.1, sampled_tiles: 300 }, ...extra,
  };
}

/** fetch double: the manifest, the fixture archive (honouring Range), the
 *  FAA service metadata/tiles; logs every URL. */
function fakeFetch(opts: { manifest?: unknown; archiveStatus?: number; serviceSubject?: string } = {}) {
  const log: string[] = [];
  const f = (async (input: string | URL | Request, init?: RequestInit) => {
    const url = String(input);
    log.push(url);
    if (url.startsWith(`${BASE}/${AERO_BAKE_MANIFEST_KEY}`)) {
      return opts.manifest === undefined ? new Response("", { status: 404 }) : new Response(JSON.stringify(opts.manifest), { status: 200 });
    }
    if (url.startsWith(`${BASE}/tiles/faa/`)) {
      if (opts.archiveStatus && opts.archiveStatus !== 206) return new Response("", { status: opts.archiveStatus });
      const h = new Headers(init?.headers as HeadersInit);
      const m = /bytes=(\d+)-(\d+)/.exec(h.get("range") || "");
      assert.ok(m, "every archive read is a range request");
      const a = Number(m![1]), b = Math.min(Number(m![2]), FIXTURE.length - 1);
      return new Response(new Uint8Array(FIXTURE.subarray(a, b + 1)), { status: 206, headers: { etag: '"fx"' } });
    }
    if (url.includes("/MapServer?f=json")) {
      return new Response(JSON.stringify({ minLOD: 8, maxLOD: 12, documentInfo: { subject: opts.serviceSubject ?? "Updated with the latest charts on 07-09-2026." } }), { status: 200 });
    }
    if (url.includes("/MapServer/tile/")) {
      return new Response(new Uint8Array([0xff, 0xd8, 0xff, 0xe0, 7, 7]), { status: 200 });
    }
    return new Response("", { status: 404 });
  }) as typeof fetch;
  return { f, log };
}

function svcWith(fetchImpl: typeof fetch) {
  return createAeroChartService({
    fetchImpl, now: () => NOW, env: { R2_PUBLIC_URL: BASE } as NodeJS.ProcessEnv,
    tmpDir: fs.mkdtempSync(path.join(os.tmpdir(), "aero-bake-")),
  });
}

// ── pure ─────────────────────────────────────────────────────────────────────

test("manifest: well-formed entries parse newest-first with their previous edition; malformed ones are dropped", () => {
  const m = parseBakeManifest({ families: {
    sectional: { ...entry("2026-10-29"), previous: entry("2026-09-03") },
    tac: { ...entry("2026-09-03"), key: "tiles/faa/tac/../../etc.pmtiles" }, // not the run's own key shape
    ifrlow: { edition: "Sept 3", key: "x" },
    ifrhigh: { ...entry("2026-09-03", { key: "tiles/faa/ifrhigh/2026-09-03.pmtiles", min_zoom: 9, max_zoom: 5 }) },
  } }, AERO_CHART_IDS);
  assert.deepEqual(m.sectional?.map((e) => e.edition), ["2026-10-29", "2026-09-03"]);
  assert.equal(m.sectional?.[0].verify?.coverage, 0.999);
  assert.equal(m.tac, undefined, "a key outside tiles/faa/<chart>/<edition>.pmtiles is never followed");
  assert.equal(m.ifrlow, undefined);
  assert.equal(m.ifrhigh, undefined, "min_zoom > max_zoom is rejected");
  assert.deepEqual(parseBakeManifest(null, AERO_CHART_IDS), {});
  assert.deepEqual(parseBakeManifest({ families: "x" }, AERO_CHART_IDS), {});
});

test("switch rule: a bake is served only once in effect AND newer than the FAA service's edition", () => {
  const list = parseBakeManifest({ families: { sectional: { ...entry("2026-10-29"), previous: entry("2026-09-03") } } }, AERO_CHART_IDS).sectional!;
  // the 10-29 cycle is posted early but not in force yet -> the 09-03 bake
  assert.equal(chooseBake(list, "2026-07-09", "2026-10-06")?.edition, "2026-09-03");
  // once 10-29 arrives it takes over
  assert.equal(chooseBake(list, "2026-07-09", "2026-10-29")?.edition, "2026-10-29");
  // the FAA service caught up -> its own tiles again (no reason to differ)
  assert.equal(chooseBake(list, "2026-09-03", "2026-10-06"), null);
  // service metadata unreachable -> an effective bake is still the honest answer
  assert.equal(chooseBake(list, null, "2026-10-06")?.edition, "2026-09-03");
  assert.equal(chooseBake(undefined, "2026-07-09", "2026-10-06"), null);
  assert.equal(chooseBake([], null, "2026-10-06"), null);
});

test("editionInfo: an effective, newer bake becomes the edition (source own-bake, its own cycle dates)", () => {
  const list = parseBakeManifest({ families: { sectional: entry("2026-09-03") } }, AERO_CHART_IDS).sectional!;
  const e = editionInfo("2026-07-09", NOW, list);
  assert.equal(e.source, "own-bake");
  assert.equal(e.edition, "2026-09-03");
  assert.equal(e.expires, "2026-10-29");
  assert.equal(e.expired, false);
  assert.equal(e.behindCurrentCycle, false);
  assert.equal(e.bake?.key, "tiles/faa/sectional/2026-09-03.pmtiles");
  const svc = editionInfo("2026-07-09", NOW);
  assert.equal(svc.source, "service-metadata");
  assert.equal("bake" in svc, false, "the service-path EditionInfo shape is unchanged");
});

test("WebP is sniffed as an image (the bake's tile format)", () => {
  assert.equal(sniffImageType(Buffer.from("RIFF\x00\x00\x00\x00WEBPVP8 ", "latin1")), "image/webp");
  assert.equal(sniffImageType(Buffer.from("RIFF\x00\x00\x00\x00WAVEfmt ", "latin1")), null);
});

// ── reading the archive the Python bake writes ──────────────────────────────

test("reader: tiles written by the Python bake read back over HTTP ranges; absent tiles are null", async () => {
  const { f, log } = fakeFetch();
  const r = createBakeReader(BASE, f);
  const red = await r.tile("tiles/faa/sectional/2026-09-03.pmtiles", 2, 0, 1);
  assert.ok(red);
  assert.equal(sniffImageType(red!), "image/webp");
  const blue = await r.tile("tiles/faa/sectional/2026-09-03.pmtiles", 11, 350, 740);
  assert.equal(sniffImageType(blue!), "image/webp");
  assert.equal(await r.tile("tiles/faa/sectional/2026-09-03.pmtiles", 11, 351, 740), null);
  assert.ok(log.every((u) => u === `${BASE}/tiles/faa/sectional/2026-09-03.pmtiles`));
  const before = log.length;
  await r.tile("tiles/faa/sectional/2026-09-03.pmtiles", 5, 8, 12);
  assert.ok(log.length - before <= 1, "header + directory are cached: one more range read per tile at most");
});

test("RangeFetchSource: a server ignoring Range (200 + whole body) is sliced to the asked bytes; errors throw", async () => {
  const whole = (async () => new Response(new Uint8Array(FIXTURE), { status: 200 })) as unknown as typeof fetch;
  const got = await new RangeFetchSource("u", whole).getBytes(0, 7);
  assert.equal(Buffer.from(got.data).toString("latin1"), "PMTiles");
  const bad = (async () => new Response("", { status: 403 })) as unknown as typeof fetch;
  await assert.rejects(new RangeFetchSource("u", bad).getBytes(0, 7), /HTTP 403/);
});

// ── integration with the chart service ─────────────────────────────────────

test("service: with an effective newer bake, tiles come from the archive (WebP), one range read then the tmp cache", async () => {
  const { f, log } = fakeFetch({ manifest: { families: { sectional: entry("2026-09-03") } } });
  const svc = svcWith(f);
  const a = await svc.getTile("sectional", 2, 0, 1);
  assert.equal(a.edition.source, "own-bake");
  assert.equal(a.outcome.kind, "tile");
  assert.equal(a.outcome.kind === "tile" && a.outcome.contentType, "image/webp");
  assert.equal(a.outcome.kind === "tile" && a.outcome.from, "bake");
  const reads = log.filter((u) => u.includes("/tiles/faa/sectional/")).length;
  const b = await svc.getTile("sectional", 2, 0, 1);
  assert.equal(b.outcome.kind === "tile" && b.outcome.from, "tmp");
  assert.equal(log.filter((u) => u.includes("/tiles/faa/sectional/")).length, reads, "second request: no archive read");
  // a tile the bake does not have is empty (no FAA service read-through)
  const e = await svc.getTile("sectional", 11, 1, 1);
  assert.equal(e.outcome.kind, "empty");
  assert.equal(log.some((u) => u.includes("/MapServer/tile/")), false, "the FAA tile service is never touched");
  // past the bake's native level: out of range (the map enlarges z11)
  const deep = await svc.getTile("sectional", 12, 700, 1480);
  assert.equal(deep.outcome.kind === "empty" && deep.outcome.from, "out-of-range");
  // charts without a bake keep the FAA path
  const tac = await svc.getTile("tac", 10, 200, 400);
  assert.equal(tac.edition.source, "service-metadata");
});

test("service: a bake that is posted but not in effect yet (or older than the service) changes nothing", async () => {
  const early = svcWith(fakeFetch({ manifest: { families: { sectional: entry("2026-10-29") } } }).f);
  assert.equal((await early.getTile("sectional", 9, 80, 180)).edition.source, "service-metadata");
  const stale = svcWith(fakeFetch({ manifest: { families: { sectional: entry("2026-09-03") } }, serviceSubject: "Updated with the latest charts on 09-03-2026." }).f);
  assert.equal((await stale.getTile("sectional", 9, 80, 180)).edition.source, "service-metadata");
});

test("service: an unreadable archive falls back to the FAA tile for that request only — never cached", async () => {
  const { f } = fakeFetch({ manifest: { families: { sectional: entry("2026-09-03") } }, archiveStatus: 503 });
  const svc = svcWith(f);
  const r = await svc.getTile("sectional", 9, 80, 180);
  assert.equal(r.edition.source, "own-bake");
  assert.equal(r.outcome.kind, "tile");
  assert.equal(r.outcome.kind === "tile" && r.outcome.from, "upstream");
  assert.equal(r.outcome.kind === "tile" && r.outcome.noStore, true);
  const st = await svc.status();
  assert.equal(st.cache.bakeErrors, 1);
  assert.equal(st.cache.bakeFallbacks, 1);
  // the HTTP layer marks it no-store
  const headers: Record<string, string> = {};
  const res = {
    statusCode: 0, headersSent: false,
    setHeader(k: string, v: string) { headers[k.toLowerCase()] = v; },
    status(c: number) { this.statusCode = c; return this; },
    end() { return this; }, json() { return this; },
  };
  await handleAeroTile(svc, { params: { chart: "sectional", z: "9", x: "80", y: "180" }, query: { e: "2026-09-03" } } as never, res as never);
  assert.equal(headers["cache-control"], "no-store");
});

test("status + registry: own-bake rows advertise the baked band (z2..native) and the bake's provenance", async () => {
  const svc = svcWith(fakeFetch({ manifest: { families: { sectional: entry("2026-09-03") } } }).f);
  const st = await svc.status();
  const sec = st.charts.find((c) => c.id === "sectional")!;
  assert.equal(sec.editionSource, "own-bake");
  assert.equal(sec.tileSource, "own-bake");
  assert.equal(sec.serviceEdition, "2026-07-09");
  assert.equal(sec.servedMinzoom, 2);
  assert.equal(sec.maxzoom, 11);
  assert.equal(sec.minzoom, 8);
  assert.equal(sec.tiles, "/tiles/aero/sectional/{z}/{x}/{y}?e=2026-09-03");
  assert.equal(sec.bake?.verify?.sampled_tiles, 300);
  const tac = st.charts.find((c) => c.id === "tac")!;
  assert.equal(tac.tileSource, "faa-service");
  assert.deepEqual(st.ownBake.published.sectional, ["2026-09-03"]);
  const reg = svc.registryEntries().find((c) => c.id === "sectional")!;
  assert.equal(reg.tileSource, "own-bake");
  assert.equal(reg.edition, "2026-09-03");
  assert.equal(reg.maxzoom, 11);
});

test("prefetch never reads the FAA service for a chart served from our own bake", async () => {
  const { f, log } = fakeFetch({ manifest: { families: {
    sectional: entry("2026-09-03"),
    tac: { ...entry("2026-09-03"), key: "tiles/faa/tac/2026-09-03.pmtiles" },
    ifrlow: { ...entry("2026-09-03"), key: "tiles/faa/ifrlow/2026-09-03.pmtiles" },
    ifrhigh: { ...entry("2026-09-03"), key: "tiles/faa/ifrhigh/2026-09-03.pmtiles" },
  } } });
  const r2 = { configured: true } as never;
  const svc = createAeroChartService({ fetchImpl: f, now: () => NOW, env: { R2_PUBLIC_URL: BASE } as NodeJS.ProcessEnv, r2,
    tmpDir: fs.mkdtempSync(path.join(os.tmpdir(), "aero-bake-")), sleep: async () => undefined });
  await svc.runPrefetch();
  assert.equal(log.some((u) => u.includes("/MapServer/tile/")), false);
});

test("manifest unreachable: the FAA service path is unchanged", async () => {
  const svc = svcWith(fakeFetch().f);
  const r = await svc.getTile("sectional", 9, 80, 180);
  assert.equal(r.edition.source, "service-metadata");
  assert.equal(r.outcome.kind === "tile" && r.outcome.from, "upstream");
});
