#!/usr/bin/env python3
"""
illiquid_universe_probe_regime.py — REGIME-CONDITIONED check on the
open_questions.md entry filed 2026-07-24 ("Does mean_reversion have a
real, exploitable edge specifically in illiquid small-caps, or is the
2026-07-24 probe result a single-sample artifact?").

WHY THIS SCRIPT, AND WHY NOW: REASONING STANDARD #2 (CLAUDE.md) — "never
evaluate a rule/strategy on pooled results alone — split by regime...
'works overall' often means 'works in the regime that dominated the
sample'" — is a mandatory check BEFORE crediting any signal, and it had
not yet been applied to this finding. Step 2 (TRAIN/TEST SPLIT,
illiquid_universe_probe_traintest.py) found the illiquid mean_reversion
Sharpe SIGN-FLIPS between the early and late halves of the same 4y
window (negative early, strongly positive late) while the
illiquid-beats-moderate SPREAD stayed directionally stable. Step 3
(SIGNIFICANCE TEST, illiquid_universe_probe_significance.py) then found
that spread significant on the POOLED 4y sample — but a pooled bootstrap
over an unexplained, sign-flipping sub-series is exactly the situation
Reasoning Standard #2 warns about: an arbitrary calendar-time split
(early half / late half) is not the same question as "does this hold
across market REGIMES," and the two 4y halves almost certainly do not
carry the same regime mix. This script answers the more precise
question directly, using the trades already generated by the existing
strategy logic (nothing re-tuned, nothing re-fit) instead of assuming
calendar time is a proxy for regime.

This is diagnostic, not step 4 or step 5 of the filed LADDER PATH — it
does not re-threshold anything and is not itself a SIGNAL-gate pass. It
exists to tell a future step-4 session whether the sign-flip found in
step 2 is EXPLAINED by regime composition (in which case any re-tuning
effort should be regime-conditional from the start) or is NOT explained
by regime (in which case the instability is a more basic problem that
re-thresholding alone would not fix, and step 4/5 should be reconsidered
or at minimum flagged as higher-risk before any live code change).

PRIOR, stated 2026-07-31 BEFORE running (Reasoning Standard #10): thin
order books mechanically exhausting retail-panic-driven oversold
conditions (the structural story in the original 2026-07-24 entry) predicts
the illiquid mean_reversion edge should be CONCENTRATED in higher-vol
regimes (BEAR/CAUTION/PANIC) where oversold spikes are sharper and more
mechanical, and comparatively muted in BULL (fewer oversold triggers at
all in a trending-up tape). If regime, not calendar time, is the real
axis, PANIC/BEAR/CAUTION buckets should show a cleaner illiquid-beats-
moderate spread than NEUTRAL/BULL — and the early/late sign flip should
correspond to a shift in which regimes dominated each half.
COUNTER-PRIOR (Reasoning Standard #4): with only 147 pooled illiquid
trades over 4y split five ways by regime, most per-regime buckets will
be thin (a few dozen trades or fewer) — this script can show whether the
DIRECTION of a regime effect is plausible, it cannot itself deliver a
new significance-tested checkpoint at that resolution. Framed here as
descriptive, exploratory evidence only, same evidentiary weight as the
original 2026-07-24 finding before its own steps 1-3 — NOT a step
3-equivalent significance pass.

METHOD: reuses the ORIGINAL pinned 2026-07-24 ILLIQUID/MODERATE ticker
lists (illiquid_universe_probe.ILLIQUID/MODERATE) for continuity with
steps 2-3 (LIQUID is excluded here — already flagged in every prior step
as underpowered for mean_reversion, 11 trades across 7 tickers, and
splitting that further by regime would be even less meaningful). For
each ticker: fetch the full 4y bars once, run
backtest_v2.run_backtest(ticker, "mean_reversion", years, bars=..., spy=...,
vxx=...) and keep its `all_trades["mean_reversion"]` list (each trade
already carries `date_entry`). Regime label per trade comes from
backtest_v2.regime_series(spy, vxx) — the EXACT SAME function
simulate() calls internally to gate params during the backtest itself —
looked up by the trade's own `date_entry` (falls back to "NEUTRAL" on a
missing date, mirroring simulate()'s own `regime_by_date.get(d,
"NEUTRAL")` fallback). This is a READ of the already-computed regime
series, not a re-derivation with different logic — no drift from what
the backtest itself used to decide when to trade.

METRIC CHOICE (deliberate, and a real limitation — stated up front):
per-regime SHARPE is not computed here. Sharpe needs a return SERIES,
and a regime-sliced sub-series of an equity curve that a trade may span
into or out of (a position can be opened in one regime and closed in
another) does not have a clean definition without re-simulating with
regime transitions as forced exits — a materially different, more
invasive experiment this script does not attempt. Instead this script
reports, per regime bucket: n_trades, win_rate_pct, and mean_net_pct
(mean of each trade's own realized % return, `net_pct` — a per-trade,
not a portfolio-level, statistic). This is a coarser metric than steps
1-3's Sharpe; comparisons between this script's output and the earlier
steps' Sharpe readings should not be treated as apples-to-apples.

Run with: python3 scripts/illiquid_universe_probe_regime.py
(network calls: 1 bars fetch per ticker (17 total: 10 illiquid + 7
moderate) + 1 shared SPY fetch + 1 shared VXX fetch — no API key
required, same as the prior probe scripts.)
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import illiquid_universe_probe as orig  # noqa: E402

YEARS = orig.YEARS  # 4
REGIME_LEVELS = ("PANIC", "BEAR", "CAUTION", "NEUTRAL", "BULL")


def build_regime_lookup(spy_bars: dict, vxx_bars: dict | None) -> dict:
    """Thin wrapper around backtest_v2.regime_series — same function
    simulate() uses internally to gate params, so labels here are
    identical to what the backtest itself saw at each date, not a
    parallel re-derivation that could silently disagree."""
    from backtest_v2 import regime_series
    labels, _quality = regime_series(spy_bars, vxx_bars)
    return dict(zip(spy_bars["date"], labels))


def tag_trades_with_regime(trades: list, regime_lookup: dict) -> list:
    """Pure, network-free: attaches each trade's entry-date regime label.
    Falls back to NEUTRAL on a date missing from the lookup, mirroring
    simulate()'s own regime_by_date.get(d, "NEUTRAL") fallback exactly."""
    tagged = []
    for t in trades:
        regime = regime_lookup.get(t["date_entry"], "NEUTRAL")
        tagged.append({**t, "regime": regime})
    return tagged


def aggregate_by_regime(tagged_trades: list) -> dict:
    """Pure, network-free: n_trades / win_rate_pct / mean_net_pct per
    regime bucket. Buckets with zero trades are omitted (an empty bucket
    says nothing, not "0% win rate")."""
    by_regime = {}
    for t in tagged_trades:
        by_regime.setdefault(t["regime"], []).append(t)
    out = {}
    for regime, rows in by_regime.items():
        wins = sum(1 for r in rows if r["net_pct"] > 0)
        out[regime] = {
            "n_trades": len(rows),
            "win_rate_pct": round(100 * wins / len(rows), 1),
            "mean_net_pct": round(sum(r["net_pct"] for r in rows) / len(rows), 3),
        }
    return out


def run_group_regime(tickers, years=YEARS) -> dict:
    """Per-group orchestration: shared SPY/VXX fetch, per-ticker bars
    fetch + mean_reversion-only backtest, regime tagging, aggregation.
    Mirrors illiquid_universe_probe_traintest.run_split_group's shared-
    fetch pattern (SPY/VXX fetched once, reused for every ticker)."""
    from backtest_v2 import run_backtest, fetch_bars

    days = int(years * 365) + 400
    spy_bars = fetch_bars("SPY", days)
    try:
        vxx_bars = fetch_bars("VXX", days)
    except Exception:
        vxx_bars = None  # degrade exactly like run_backtest's own live-fetch path

    regime_lookup = build_regime_lookup(spy_bars, vxx_bars)

    all_tagged = []
    errors = []
    for t in tickers:
        try:
            bars = fetch_bars(t, days)
            resp = run_backtest(t, "mean_reversion", years, bars=bars,
                                 spy=spy_bars, vxx=vxx_bars)
        except Exception as e:
            errors.append({"ticker": t, "error": str(e)[:200]})
            continue
        trades = resp["all_trades"].get("mean_reversion", [])
        all_tagged.extend(tag_trades_with_regime(trades, regime_lookup))

    return {
        "n_tickers": len(tickers),
        "n_errors": len(errors),
        "errors": errors,
        "total_trades": len(all_tagged),
        "by_regime": aggregate_by_regime(all_tagged),
    }


if __name__ == "__main__":
    results = {}
    for name, tickers in [("illiquid", orig.ILLIQUID), ("moderate", orig.MODERATE)]:
        print(f"=== {name} (n={len(tickers)}) ===", file=sys.stderr)
        results[name] = run_group_regime(tickers)
        print(json.dumps(results[name], indent=2), file=sys.stderr)

    print(json.dumps(results, indent=2))
